
 - name: Download OpenStack vJSA image to httpd repository
   hosts: localhost
   connection: local
   gather_facts: no
   tasks:
   - name: Download vJSA image
     command:  openstack image save --file /data/{{jsa_hostname}}{{rev}}-image.qcow2 {{jsa_hostname}}{{rev}}-image
     environment:
        OS_USERNAME: "{{OSUSERNAME}}"
        OS_PASSWORD: "{{OSPASSWORD}}"
        OS_AUTH_URL: "{{OSAUTHURL}}"
        OS_PROJECT_NAME: "{{OSPROJECTNAME}}"
     tags:
     - skip_ansible_lint
   delay: 2400
